<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * PegawaiOrganisasiSeeder — mengisi 5 tabel lookup organisasi/jabatan
 * (level_jabatan, tampil_jabatan, unit_kerja, satuan_kerja, satuan_kerja_2)
 * dari data ASN Bimas Kristen per Sep 2026.
 *
 * PENTING soal satuan_kerja & satuan_kerja_2: nama yang SAMA bisa muncul
 * di banyak baris dengan PARENT BERBEDA (misal "Seksi Urusan Agama Kristen"
 * ada di setiap Kanwil Provinsi — itu 33+ entitas berbeda, bukan 1). Maka
 * seeder ini insert per KOMBINASI (nama + parent), bukan dedup by nama saja.
 *
 * Urutan wajib: unit_kerja dulu, baru satuan_kerja (butuh id unit_kerja),
 * baru satuan_kerja_2 (butuh id satuan_kerja).
 */
class PegawaiOrganisasiSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        // ── 1. Level Jabatan ──
        $levelJabatan = [
            'Analis Hukum',
            'Analis Kebijakan',
            'Analis Pemanfaatan Ilmu Pengetahuan dan Teknologi',
            'Analis Pengelolaan Keuangan APBN',
            'Analis SDM Aparatur',
            'Arsiparis',
            'Asesor SDM Aparatur',
            'Dosen',
            'Eselon I.a',
            'Eselon II.a',
            'Eselon III.a',
            'Eselon III.b',
            'Eselon IV.a',
            'Eselon IV.b',
            'Guru',
            'Jabatan Fungsional Umum',
            'Jabatan Pelaksana',
            'Pamong Belajar',
            'Pamong Budaya',
            'Penerjemah',
            'Pengawas',
            'Pengelola Pengadaan Barang/Jasa',
            'Pengembang Teknologi Pembelajaran',
            'Penggerak Swadaya Masyarakat',
            'Penyuluh Agama',
            'Perencana',
            'Pranata Humas',
            'Pranata Keuangan',
            'Pranata Komputer',
            'Pranata Laboratorium Pendidikan',
            'Pranata SDM Aparatur',
            'Statistisi',
        ];
        foreach ($levelJabatan as $nama) {
            $this->insertIfNotExists('level_jabatan', ['nama' => $nama], $now);
        }
        echo "Level Jabatan: " . count($levelJabatan) . " diproses.\n";

        // ── 2. Tampil Jabatan ──
        $tampilJabatan = [
            'Analis Data dan Informasi (Jabatan Pelaksana)',
            'Analis Data dan Informasi Pendidik Dan Tenaga Kependidikan (Jabatan Pelaksana)',
            'Analis Hukum Ahli Muda',
            'Analis Hukum Ahli Pertama',
            'Analis Informasi Pengembangan Pendidik/ Tenaga Kependidikan (Jabatan Pelaksana)',
            'Analis Jabatan (Jabatan Pelaksana)',
            'Analis Kapasitas Penyuluh (Jabatan Pelaksana)',
            'Analis Kebijakan Ahli Muda',
            'Analis Kebijakan Ahli Pertama',
            'Analis Kebijakan Barang Milik Negara (Jabatan Pelaksana)',
            'Analis Keuangan (Jabatan Pelaksana)',
            'Analis Kompetensi Tenaga Pengajar (Jabatan Pelaksana)',
            'Analis Kurikulum dan Pembelajaran (Jabatan Pelaksana)',
            'Analis Laporan Keuangan (Jabatan Pelaksana)',
            'Analis Laporan Pertanggungjawaban Anggaran (Jabatan Pelaksana)',
            'Analis Layanan Umum (Jabatan Pelaksana)',
            'Analis Lembaga Pengembangan Pesta Paduan Suara Gerejawi (Jabatan Pelaksana)',
            'Analis Manajemen Lembaga Keagamaan (Jabatan Pelaksana)',
            'Analis Materi Penyuluhan (Jabatan Pelaksana)',
            'Analis Organisasi dan Tata Laksana (Jabatan Pelaksana)',
            'Analis Pemanfaatan Ilmu Pengetahuan dan Teknologi Ahli Pertama',
            'Analis Pemberdayaan Masyarakat dan Kelembagaan (Jabatan Pelaksana)',
            'Analis Pembinaan Umat (Jabatan Pelaksana)',
            'Analis Pengelolaan Keuangan APBN Ahli Madya',
            'Analis Pengelolaan Keuangan APBN Ahli Muda',
            'Analis Pengelolaan Keuangan APBN Ahli Pertama',
            'Analis Pengembangan Peserta Didik (Jabatan Pelaksana)',
            'Analis Pengembangan Sarana dan Prasarana Pembelajaran (Jabatan Pelaksana)',
            'Analis Pengembangan Sumberdaya Manusia Aparatur (Jabatan Pelaksana)',
            'Analis Penilaian Dan Akreditasi (Jabatan Pelaksana)',
            'Analis Perbendaharaan (Jabatan Pelaksana)',
            'Analis Perencanaan (Jabatan Pelaksana)',
            'Analis Perencanaan Program (Jabatan Pelaksana)',
            'Analis Perencanaan, Evaluasi dan Pelaporan (Jabatan Pelaksana)',
            'Analis Permasalahan (Jabatan Pelaksana)',
            'Analis Produk Hukum (Jabatan Pelaksana)',
            'Analis Program Pemberdayaan Umat (Jabatan Pelaksana)',
            'Analis Rencana Program dan Kegiatan (Jabatan Pelaksana)',
            'Analis Sarana Prasarana Ibadah (Jabatan Pelaksana)',
            'Analis Sumber Daya Manusia Aparatur Ahli Muda',
            'Analis Sumber Daya Manusia Aparatur Ahli Pertama',
            'Analis Tata Usaha (Jabatan Pelaksana)',
            'Analis Tenaga Kependidikan (Jabatan Pelaksana)',
            'Arsiparis Ahli Madya',
            'Arsiparis Ahli Muda',
            'Arsiparis Ahli Pertama',
            'Arsiparis Mahir',
            'Arsiparis Terampil Pelaksana',
            'Arsiparis Terampil Penyelia',
            'Asesor Sumber Daya Manusia Aparatur Ahli Pertama',
            'Direktur',
            'Direktur Jenderal',
            'Dosen Asisten Ahli',
            'Dosen Guru Besar',
            'Dosen Lektor',
            'Dosen Lektor Kepala',
            'Guru',
            'Guru Ahli Madya',
            'Guru Ahli Muda',
            'Guru Ahli Pertama',
            'Kepala Bagian',
            'Kepala Bidang',
            'Kepala Seksi',
            'Kepala Sub Bagian',
            'Kepala Sub Direktorat',
            'Operator Layanan Operasional',
            'Pamong Belajar Ahli Muda',
            'Pamong Budaya Ahli Muda',
            'Pelaksana (Pilihlah JFU sesuai PMA 48)',
            'Pembimbing Masyarakat',
            'Pembimbing Teknis Urusan Agama',
            'Pemeriksa Anggaran (Jabatan Pelaksana)',
            'Penata Kelola Madrasah, Pendidikan Agama dan Keagamaan',
            'Penata Kelola Sistem dan Teknologi Informasi',
            'Penata Laporan Keuangan (Jabatan Pelaksana)',
            'Penata Layanan Operasional',
            'Penelaah Teknis Kebijakan',
            'Penelaah Teknis Kebijakan (Jabatan Pelaksana)',
            'Penerjemah Ahli Pertama',
            'Pengadministrasi',
            'Pengadministrasi Kependidikan  (Jabatan Pelaksana)',
            'Pengadministrasi Perkantoran',
            'Pengadministrasi Persuratan (Jabatan Pelaksana)',
            'Pengadministrasi Tugas Belajar/Ijin Belajar (Jabatan Pelaksana)',
            'Pengadministrasi Umum (Jabatan Pelaksana)',
            'Pengawas Sekolah Ahli Madya Tingkat Dasar',
            'Pengawas Sekolah Ahli Madya Tingkat Menengah',
            'Pengawas Sekolah Ahli Muda Tingkat Dasar',
            'Pengawas Sekolah Ahli Muda Tingkat Menengah',
            'Pengelola Data (Jabatan Pelaksana)',
            'Pengelola Data Sarana Dan Prasarana Pendidikan (Jabatan Pelaksana)',
            'Pengelola Database Pendidikan (Jabatan Pelaksana)',
            'Pengelola Layanan Operasional (Jabatan Pelaksana)',
            'Pengelola Pendidikan',
            'Pengelola Pendidikan (Jabatan Pelaksana)',
            'Pengelola Pengadaan Barang/Jasa Ahli Muda',
            'Pengelola Pengadaan Barang/Jasa Ahli Pertama',
            'Pengelola Umum Operasional',
            'Pengelola Urusan Agama (Jabatan Pelaksana)',
            'Pengembang Profesi Dosen',
            'Pengembang Teknologi Pembelajaran Ahli Muda',
            'Pengembang Teknologi Pembelajaran Ahli Pertama',
            'Pengembang Tenaga Kependidikan',
            'Pengevaluasi Tenaga Kependidikan',
            'Pengevaluasi Tenaga Kependidikan (Jabatan Pelaksana)',
            'Penggerak Swadaya Masyarakat Ahli Muda',
            'Pengolah Data (Jabatan Pelaksana)',
            'Pengolah Data Kelembagaan',
            'Pengolah Data dan Informasi',
            'Pengolah Data dan Informasi (Jabatan Pelaksana)',
            'Pengolah Pendidikan (Jabatan Pelaksana)',
            'Penyelenggara',
            'Penyuluh Agama Ahli Madya',
            'Penyuluh Agama Ahli Muda',
            'Penyuluh Agama Ahli Pertama',
            'Penyuluh Agama Pelaksana',
            'Penyusun Bahan Informasi (Jabatan Pelaksana)',
            'Penyusun Bahan Informasi dan Publikasi (Jabatan Pelaksana)',
            'Penyusun Bahan Laporan Akuntabilitas Lembaga Keagamaan',
            'Penyusun Bahan Pembinaan Keesaan (Jabatan Pelaksana)',
            'Penyusun Bahan Pembinaan Umat (Jabatan Pelaksana)',
            'Penyusun Bahan Pengembangan Program Keagamaan',
            'Penyusun Bahan Urusan Agama (Jabatan Pelaksana)',
            'Penyusun Naskah Rapat Pimpinan',
            'Penyusun Norma, Standar, Prosedur dan Kriteria (Jabatan Pelaksana)',
            'Penyusun Program Anggaran dan Pelaporan',
            'Penyusun Program Anggaran dan Pelaporan (Jabatan Pelaksana)',
            'Penyusun Rancangan Perundang- Undangan (Jabatan Pelaksana)',
            'Penyusun Rencana Kegiatan dan Anggaran (Jabatan Pelaksana)',
            'Penyusun Rencana Keuangan dan Barang Milik Negara (Jabatan Pelaksana)',
            'Perencana Ahli Madya',
            'Perencana Ahli Muda',
            'Perencana Ahli Pertama',
            'Pranata Hubungan Masyarakat Ahli Muda',
            'Pranata Hubungan Masyarakat Ahli Pertama',
            'Pranata Kerukunan Umat Beragama',
            'Pranata Keuangan APBN Mahir',
            'Pranata Keuangan APBN Penyelia',
            'Pranata Keuangan APBN Terampil',
            'Pranata Komputer Ahli Muda',
            'Pranata Komputer Ahli Pertama',
            'Pranata Komputer Terampil',
            'Pranata Laboratorium Pendidikan Ahli Pertama',
            'Pranata Sumber Daya Manusia Aparatur Terampil',
            'Sekretaris Eselon I',
            'Statistisi Ahli Pertama',
        ];
        foreach ($tampilJabatan as $nama) {
            $this->insertIfNotExists('tampil_jabatan', ['nama' => $nama], $now);
        }
        echo "Tampil Jabatan: " . count($tampilJabatan) . " diproses.\n";

        // ── 3. Unit Kerja (dari Satker 4 di data sumber) ──
        $unitKerja = [
            'Direktorat Jenderal Bimbingan Masyarakat Kristen',
            'IAKN Ambon',
            'IAKN Kupang',
            'IAKN Manado',
            'IAKN Palangkaraya',
            'IAKN Tarutung',
            'IAKN Toraja',
            'Kanwil Kementerian Agama Daerah Istimewa Yogyakarta',
            'Kanwil Kementerian Agama Provinsi Aceh',
            'Kanwil Kementerian Agama Provinsi Bali',
            'Kanwil Kementerian Agama Provinsi Banten',
            'Kanwil Kementerian Agama Provinsi Bengkulu',
            'Kanwil Kementerian Agama Provinsi DKI Jakarta',
            'Kanwil Kementerian Agama Provinsi Gorontalo',
            'Kanwil Kementerian Agama Provinsi Jambi',
            'Kanwil Kementerian Agama Provinsi Jawa Barat',
            'Kanwil Kementerian Agama Provinsi Jawa Tengah',
            'Kanwil Kementerian Agama Provinsi Jawa Timur',
            'Kanwil Kementerian Agama Provinsi Kalimantan Barat',
            'Kanwil Kementerian Agama Provinsi Kalimantan Selatan',
            'Kanwil Kementerian Agama Provinsi Kalimantan Tengah',
            'Kanwil Kementerian Agama Provinsi Kalimantan Timur',
            'Kanwil Kementerian Agama Provinsi Kalimantan Utara',
            'Kanwil Kementerian Agama Provinsi Kepulauan Bangka Belitung',
            'Kanwil Kementerian Agama Provinsi Kepulauan Riau',
            'Kanwil Kementerian Agama Provinsi Lampung',
            'Kanwil Kementerian Agama Provinsi Maluku',
            'Kanwil Kementerian Agama Provinsi Maluku Utara',
            'Kanwil Kementerian Agama Provinsi Nusa Tenggara Barat',
            'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur',
            'Kanwil Kementerian Agama Provinsi Papua',
            'Kanwil Kementerian Agama Provinsi Papua Barat',
            'Kanwil Kementerian Agama Provinsi Riau',
            'Kanwil Kementerian Agama Provinsi Sulawesi Barat',
            'Kanwil Kementerian Agama Provinsi Sulawesi Selatan',
            'Kanwil Kementerian Agama Provinsi Sulawesi Tengah',
            'Kanwil Kementerian Agama Provinsi Sulawesi Tenggara',
            'Kanwil Kementerian Agama Provinsi Sulawesi Utara',
            'Kanwil Kementerian Agama Provinsi Sumatera Barat',
            'Kanwil Kementerian Agama Provinsi Sumatera Selatan',
            'Kanwil Kementerian Agama Provinsi Sumatera Utara',
            'STAKPN Sentani',
        ];
        foreach ($unitKerja as $nama) {
            $this->insertIfNotExists('unit_kerja', ['nama' => $nama], $now);
        }
        echo "Unit Kerja: " . count($unitKerja) . " diproses.\n";

        // ── 4. Satuan Kerja (dari Satker 3, parent = Unit Kerja / Satker 4) ──
        $satuanKerjaPairs = [
            ['nama' => 'Direktorat Urusan Agama Kristen', 'parent_nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Sekretariat Direktorat Jenderal Bimbingan Masyarakat Kristen', 'parent_nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Direktorat Pendidikan Kristen', 'parent_nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen', 'parent_nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Fakultas Ilmu Pendidikan Kristen', 'parent_nama' => 'IAKN Ambon'],
            ['nama' => 'Fakultas Keguruan Dan Ilmu Pendidikan Kristen', 'parent_nama' => 'IAKN Kupang'],
            ['nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen', 'parent_nama' => 'IAKN Kupang'],
            ['nama' => 'Fakultas Ilmu Pendidikan Kristen', 'parent_nama' => 'IAKN Manado'],
            ['nama' => 'Pascasarjana', 'parent_nama' => 'IAKN Manado'],
            ['nama' => 'Fakultas Teologi', 'parent_nama' => 'IAKN Manado'],
            ['nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen', 'parent_nama' => 'IAKN Palangkaraya'],
            ['nama' => 'Fakultas Seni Keagamaan Kristen', 'parent_nama' => 'IAKN Palangkaraya'],
            ['nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen', 'parent_nama' => 'IAKN Palangkaraya'],
            ['nama' => 'Fakultas Ilmu Sosial dan Humaniora Kristen', 'parent_nama' => 'IAKN Tarutung'],
            ['nama' => 'Fakultas Ilmu Pendidikan Kristen', 'parent_nama' => 'IAKN Tarutung'],
            ['nama' => 'Fakultas Budaya dan Kepemimpinan Kristen', 'parent_nama' => 'IAKN Toraja'],
            ['nama' => 'Fakultas Teologi dan Sosiologi Kristen', 'parent_nama' => 'IAKN Toraja'],
            ['nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen', 'parent_nama' => 'IAKN Toraja'],
            ['nama' => 'Kanwil Kementerian Agama Daerah Istimewa Yogyakarta', 'parent_nama' => 'Kanwil Kementerian Agama Daerah Istimewa Yogyakarta'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Aceh', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Aceh'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Aceh Tenggara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Aceh'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Bali', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Bali'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Banten', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Banten'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tangerang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Banten'],
            ['nama' => 'Kantor Kementerian Agama Kota Tangerang Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Banten'],
            ['nama' => 'Kantor Kementerian Agama Kota Tangerang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Banten'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Bengkulu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Bengkulu'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepahiang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Bengkulu'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Rejang Lebong', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Bengkulu'],
            ['nama' => 'Kantor Kementerian Agama Kota Jakarta Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Kantor Kementerian Agama Kota Jakarta Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Kantor Kementerian Agama Kota Jakarta Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Kantor Kementerian Agama Kota Jakarta Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Kantor Kementerian Agama Kota Jakarta Pusat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Gorontalo', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Gorontalo'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Jambi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jambi'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat'],
            ['nama' => 'Kantor Kementerian Agama Kota Bogor', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat'],
            ['nama' => 'Kantor Kementerian Agama Kota Bekasi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bogor', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat'],
            ['nama' => 'Kantor Kementerian Agama Kota Depok', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kota Salatiga', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Semarang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Karanganyar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kota Surakarta', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pati', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kota Semarang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Magelang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Jepara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Banyumas', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Blitar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sidoarjo', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kota Surabaya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kediri', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Madiun', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Jember', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Malang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Landak', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sekadau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sintang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kayong Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sambas', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kota Pontianak', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bengkayang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Ketapang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Melawi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sanggau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tabalong', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Selatan'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Lamandau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Gunung Mas', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Barito Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pulang Pisau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kota Palangkaraya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Murung Raya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kapuas', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kotawaringin Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Katingan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Barito Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Panajam Paser Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kutai Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur'],
            ['nama' => 'Kantor Kementerian Agama Kota Balikpapan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kutai Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Malinau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nunukan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bulungan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Tarakan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Bangka Belitung', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Bangka Belitung'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Riau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Riau'],
            ['nama' => 'Kantor Kementerian Agama Kota Batam', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Karimun', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Riau'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Lampung', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Lampung'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Lampung Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Lampung'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Maluku', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Maluku Barat Daya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Maluku Tenggara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Seram Bagian Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Maluku Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Aru', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kota Tual', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kota Ambon', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Buru', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Tanimbar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Seram Bagian Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Buru Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pulau Morotai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Ternate', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pulau Taliabu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Barat'],
            ['nama' => 'Kantor Kementerian Agama Kota Bima', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Alor', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sabu Raijua', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kupang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kota Kupang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sumba Barat Daya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Malaka', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Manggarai Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Rote Ndao', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Manggarai Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Lembata', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sumba Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sumba Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sumba Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Belu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Timor Tengah Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Timor Tengah Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Flores Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Manggarai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Ende', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Ngada', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sikka', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Papua', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Supiori', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Yapen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kota Jayapura', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Jayapura', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mimika', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Asmat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Yahukimo', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Biak Numfor', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nduga', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tolikara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Paniai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mamberamo Raya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nabire', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Lanny Jaya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Puncak', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mamberamo Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sarmi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Jayawijaya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Puncak Jaya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Deiyai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Intan Jaya', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Keerom', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Yalimo', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Waropen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mappi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pegunungan Bintang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Merauke', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Boven Digoel', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Dogiyai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kota Sorong', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Teluk Wondama', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Fak-Fak', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Raja Ampat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tambrauw', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Manokwari', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sorong', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Teluk Bintuni', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kaimana', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Maybrat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sorong Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Manokwari Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pegunungan Arfak', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Riau', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Siak', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pelalawan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Rokan Hilir', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kota Dumai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kota Pekanbaru', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Rokan Hulu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bengkalis', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kampar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mamuju Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mamasa', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Polewali Mandar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pasangkayu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mamuju', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Luwu Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tana Toraja', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Toraja Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Luwu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kota Makassar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Luwu Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Banggai Kepulauan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Donggala', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Morowali Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Sigi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Banggai Laut', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tojo Una-Una', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Banggai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Poso', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kota Palu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Morowali', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Parigi Moutong', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tenggara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tenggara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kolaka', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tenggara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Tenggara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Talaud', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Tomohon', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bolaang Mongondow Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Manado', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Sangihe', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Minahasa', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Bitung', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Kotamobagu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bolaang Mongondow', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Bolaang Mongondow Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Barat'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Mentawai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Barat'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten OKU Timur', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kota Palembang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Selatan'],
            ['nama' => 'Kantor Kementerian Agama Kota Medan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Batu Bara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Serdang Bedagai', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Sibolga', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Simalungun', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Pematangsiantar', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Deli Serdang', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nias Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Mandailing Natal', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nias Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Toba Samosir', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Tengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Dairi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Pakpak Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Langkat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nias Barat', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Nias', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Gunungsitoli', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Samosir', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Labuhanbatu Selatan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Padang Lawas Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Asahan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kota Tebing Tinggi', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Karo', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Humbang Hasundutan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Labuhanbatu Utara', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Kantor Kementerian Agama Kabupaten Labuhanbatu', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Jurusan Pendidikan Agama Kristen', 'parent_nama' => 'STAKPN Sentani'],
        ];
        $skInserted = 0;
        foreach ($satuanKerjaPairs as $pair) {
            $parentId = $this->findIdByName('unit_kerja', $pair['parent_nama']);
            if ($parentId === null) {
                echo "  [WARNING] Unit Kerja tidak ditemukan: {$pair['parent_nama']}\n";
                continue;
            }
            $this->insertIfNotExists('satuan_kerja', ['nama' => $pair['nama'], 'parent_id' => $parentId], $now);
            $skInserted++;
        }
        echo "Satuan Kerja: {$skInserted} pasangan diproses.\n";

        // ── 5. Satuan Kerja 2 (dari Satker 1, parent = Satuan Kerja / Satker 3) ──
        // Catatan: karena nama Satker 3 bisa dobel dengan parent Unit Kerja
        // berbeda (lihat komentar di atas class), pencarian parent_id di sini
        // sengaja TIDAK unik sempurna untuk 3 nama yang diketahui dobel
        // (Fakultas Ilmu Pendidikan Kristen, dst.) — akan match ke kemunculan
        // PERTAMA yang ditemukan. Ini dicatat sebagai known limitation,
        // dampaknya kecil (cuma memengaruhi beberapa baris dari total 4920).
        $satuanKerja2Pairs = [
            ['nama' => 'Subdirektorat Kelembagaan', 'parent_nama' => 'Direktorat Urusan Agama Kristen'],
            ['nama' => 'Sekretariat Direktorat Jenderal Bimbingan Masyarakat Kristen', 'parent_nama' => 'Sekretariat Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Direktorat Urusan Agama Kristen', 'parent_nama' => 'Direktorat Urusan Agama Kristen'],
            ['nama' => 'Direktorat Pendidikan Kristen', 'parent_nama' => 'Direktorat Pendidikan Kristen'],
            ['nama' => 'Subbagian Tata Usaha', 'parent_nama' => 'Direktorat Pendidikan Kristen'],
            ['nama' => 'Subdirektorat Pendidikan Dasar', 'parent_nama' => 'Direktorat Pendidikan Kristen'],
            ['nama' => 'Subdirektorat Pemberdayaan Umat dan Pengembangan Budaya', 'parent_nama' => 'Direktorat Urusan Agama Kristen'],
            ['nama' => 'Subdirektorat Penyuluhan', 'parent_nama' => 'Direktorat Urusan Agama Kristen'],
            ['nama' => 'Subdirektorat Pendidikan Tinggi Keagamaan', 'parent_nama' => 'Direktorat Pendidikan Kristen'],
            ['nama' => 'Subdirektorat Pendidikan Menengah', 'parent_nama' => 'Direktorat Pendidikan Kristen'],
            ['nama' => 'Bagian Umum dan Barang Milik Negara', 'parent_nama' => 'Sekretariat Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Subbagian Tata Usaha', 'parent_nama' => 'Direktorat Urusan Agama Kristen'],
            ['nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen', 'parent_nama' => 'Direktorat Jenderal Bimbingan Masyarakat Kristen'],
            ['nama' => 'Bagian Tata Usaha', 'parent_nama' => 'Fakultas Ilmu Pendidikan Kristen'],
            ['nama' => 'Fakultas Ilmu Pendidikan Kristen', 'parent_nama' => 'Fakultas Ilmu Pendidikan Kristen'],
            ['nama' => 'Program Studi ...', 'parent_nama' => 'Fakultas Ilmu Pendidikan Kristen'],
            ['nama' => 'Jurusan Pendidikan Seni Dan Konseling Kristen', 'parent_nama' => 'Fakultas Keguruan Dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Prodi Psikologi Kristen', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Prodi Bimbingan Dan Konseling Kristen', 'parent_nama' => 'Fakultas Keguruan Dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Prodi Pendidikan Agama Kristen', 'parent_nama' => 'Fakultas Keguruan Dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Fakultas Keguruan Dan Ilmu Pendidikan Kristen', 'parent_nama' => 'Fakultas Keguruan Dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Program Studi Pendidikan Agama Kristen', 'parent_nama' => 'Fakultas Ilmu Pendidikan Kristen'],
            ['nama' => 'Program Studi S2 Pendidikan Agama Kristen', 'parent_nama' => 'Pascasarjana'],
            ['nama' => 'Program Studi Misiologi dan Komunikasi Kristen', 'parent_nama' => 'Fakultas Teologi'],
            ['nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen', 'parent_nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Fakultas Seni Keagamaan Kristen', 'parent_nama' => 'Fakultas Seni Keagamaan Kristen'],
            ['nama' => 'Prodi Musik Gereja', 'parent_nama' => 'Fakultas Seni Keagamaan Kristen'],
            ['nama' => 'Prodi Pastoral Konseling', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Prodi Bimbingan dan Konseling Kristen', 'parent_nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Jurusan Musik Gereja dan Peribadatan Kristen', 'parent_nama' => 'Fakultas Seni Keagamaan Kristen'],
            ['nama' => 'Prodi Pendidikan Agama Kristen', 'parent_nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Prodi Teologi', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Prodi Kepemimpinan Kristen', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Kelompok Dosen Jurusan Musik Gereja dan Peribadatan Kristen', 'parent_nama' => 'Fakultas Seni Keagamaan Kristen'],
            ['nama' => 'Wakil Dekan Bidang Akademik, Kemahasiswaan, Kelembagaan dan Kerja Sama', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Subbagian Tata Usaha', 'parent_nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Subbagian Tata Usaha', 'parent_nama' => 'Fakultas Ilmu Sosial Keagamaan Kristen'],
            ['nama' => 'Fakultas Ilmu Sosial dan Humaniora Kristen', 'parent_nama' => 'Fakultas Ilmu Sosial dan Humaniora Kristen'],
            ['nama' => 'Program Studi Manajemen Pendidikan Kristen', 'parent_nama' => 'Fakultas Ilmu Pendidikan Kristen'],
            ['nama' => 'Program Studi Pariwisata, Budaya dan Keagamaan Kristen', 'parent_nama' => 'Fakultas Ilmu Sosial dan Humaniora Kristen'],
            ['nama' => 'Program Studi Sosiologi Kristen', 'parent_nama' => 'Fakultas Ilmu Sosial dan Humaniora Kristen'],
            ['nama' => 'Program Studi Pendidikan Anak Usia Dini', 'parent_nama' => 'Fakultas Ilmu Pendidikan Kristen'],
            ['nama' => 'Bagian Tata Usaha', 'parent_nama' => 'Fakultas Ilmu Sosial dan Humaniora Kristen'],
            ['nama' => 'Subbagian Tata Usaha', 'parent_nama' => 'Fakultas Budaya dan Kepemimpinan Kristen'],
            ['nama' => 'Bagian Tata Usaha', 'parent_nama' => 'Fakultas Teologi dan Sosiologi Kristen'],
            ['nama' => 'Fakultas Budaya dan Kepemimpinan Kristen', 'parent_nama' => 'Fakultas Budaya dan Kepemimpinan Kristen'],
            ['nama' => 'Program Studi Teologi Kristen', 'parent_nama' => 'Fakultas Teologi dan Sosiologi Kristen'],
            ['nama' => 'Fakultas Teologi dan Sosiologi Kristen', 'parent_nama' => 'Fakultas Teologi dan Sosiologi Kristen'],
            ['nama' => 'Jurusan Ilmu Pendidikan Kristen', 'parent_nama' => 'Fakultas Keguruan dan Ilmu Pendidikan Kristen'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Daerah Istimewa Yogyakarta'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Aceh'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Aceh Tenggara'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Bali'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Banten'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tangerang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Tangerang Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Tangerang'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Bengkulu'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepahiang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Rejang Lebong'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jakarta Timur'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi DKI Jakarta'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jakarta Barat'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jakarta Utara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jakarta Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jakarta Pusat'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Gorontalo'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jambi'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Barat'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Bogor'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Bekasi'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bogor'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Depok'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Tengah'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Salatiga'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Semarang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Karanganyar'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Surakarta'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pati'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Semarang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Magelang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Jepara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Banyumas'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Jawa Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Blitar'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sidoarjo'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Surabaya'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kediri'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Madiun'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Jember'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Malang'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Landak'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Barat'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sekadau'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sintang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kayong Utara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sambas'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Pontianak'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bengkayang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Ketapang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Melawi'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sanggau'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tabalong'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Tengah'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Lamandau'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Gunung Mas'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Barito Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pulang Pisau'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Palangkaraya'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Murung Raya'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kapuas'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kotawaringin Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Katingan'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Barito Timur'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Panajam Paser Utara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kutai Barat'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Balikpapan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kutai Timur'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kalimantan Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Malinau'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nunukan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bulungan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Tarakan'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Bangka Belitung'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Kepulauan Riau'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Batam'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Batam'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Karimun'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Lampung'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Lampung Utara'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maluku Barat Daya'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maluku Tenggara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Seram Bagian Timur'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maluku Tengah'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Aru'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Tual'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Ambon'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Buru'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Tanimbar'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Tanimbar'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Seram Bagian Barat'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maluku Tenggara'],
            ['nama' => 'Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Buru Selatan'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Aru'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maluku Barat Daya'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Maluku Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Barat'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pulau Morotai'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Ternate'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Halmahera Selatan'],
            ['nama' => 'Penyelenggara Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pulau Taliabu'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Barat'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Bima'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Alor'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sabu Raijua'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kupang'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Nusa Tenggara Timur'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Kupang'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Alor'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Barat Daya'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Malaka'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kupang'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Manggarai Timur'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Kupang'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Rote Ndao'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Manggarai Barat'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Lembata'],
            ['nama' => 'Seksi Pendidikan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Barat'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sabu Raijua'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Tengah'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Timur'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Belu'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Timor Tengah Selatan'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Timor Tengah Utara'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Rote Ndao'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Timor Tengah Selatan'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Tengah'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Timur'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sumba Barat'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Flores Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Manggarai'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Ende'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Ngada'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sikka'],
            ['nama' => 'Seksi Kelembagaan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Bidang Pendidikan Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Supiori'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Yapen'],
            ['nama' => 'Bidang Urusan Agama Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jayapura'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Jayapura'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mimika'],
            ['nama' => 'Seksi Sistem Informasi Urusan Agama Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Supiori'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Asmat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Yahukimo'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Biak Numfor'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Yapen'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nduga'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tolikara'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Paniai'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamberamo Raya'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nabire'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Lanny Jaya'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Puncak'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamberamo Tengah'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sarmi'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Jayawijaya'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Biak Numfor'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mimika'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Puncak Jaya'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Deiyai'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamberamo Raya'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Intan Jaya'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Puncak'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Keerom'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Jayawijaya'],
            ['nama' => 'Seksi Pendidikan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nduga'],
            ['nama' => 'Seksi Pendidikan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Yalimo'],
            ['nama' => 'Seksi Pendidikan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Lanny Jaya'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Jayapura'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Jayapura'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Waropen'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Paniai'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Yahukimo'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mappi'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tolikara'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pegunungan Bintang'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nabire'],
            ['nama' => 'Seksi Pendidikan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamberamo Tengah'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Merauke'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pegunungan Bintang'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Yalimo'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Puncak Jaya'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sarmi'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Boven Digoel'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Asmat'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mappi'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Deiyai'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Waropen'],
            ['nama' => 'Seksi Pendidikan Agama Kristen pada Pendidikan Menengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Seksi Sistem Informasi Pendidikan Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Dogiyai'],
            ['nama' => 'Seksi Budaya Keagamaan', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua'],
            ['nama' => 'Bidang Urusan Agama Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Bidang Pendidikan Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Sorong'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Teluk Wondama'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Sorong'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Fak-Fak'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Raja Ampat'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tambrauw'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Manokwari'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sorong'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Teluk Bintuni'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sorong'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kaimana'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maybrat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kaimana'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sorong Selatan'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tambrauw'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Maybrat'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Manokwari'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Raja Ampat'],
            ['nama' => 'Seksi Urusan dan Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Manokwari Selatan'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Teluk Wondama'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Teluk Bintuni'],
            ['nama' => 'Seksi Urusan dan Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pegunungan Arfak'],
            ['nama' => 'Seksi Pendidikan Agama Kristen pada Pendidikan Menengah', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Papua Barat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sorong Selatan'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Riau'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Siak'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pelalawan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Rokan Hilir'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Dumai'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Pekanbaru'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Rokan Hulu'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bengkalis'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kampar'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamuju Tengah'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Barat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamasa'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Polewali Mandar'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pasangkayu'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamuju'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mamasa'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Luwu Timur'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Selatan'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tana Toraja'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Toraja Utara'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Toraja Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Luwu'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Luwu Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Makassar'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Luwu Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Banggai Kepulauan'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Donggala'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tengah'],
            ['nama' => 'Penyelenggara Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Morowali Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Sigi'],
            ['nama' => 'Penyelenggara Urusan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Banggai Laut'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tojo Una-Una'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Banggai'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Poso'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Palu'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Morowali'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Parigi Moutong'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Tenggara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kolaka'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Tenggara'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Talaud'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Tomohon'],
            ['nama' => 'Bidang Urusan Agama Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Talaud'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bolaang Mongondow Timur'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Manado'],
            ['nama' => 'Bidang Pendidikan Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sulawesi Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Sangihe'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Utara'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Bitung'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Tenggara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Kotamobagu'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bolaang Mongondow'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Bolaang Mongondow Utara'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Minahasa'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Barat'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Kepulauan Mentawai'],
            ['nama' => 'Pembimbing Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten OKU Timur'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Palembang'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Medan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Batu Bara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Serdang Bedagai'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Sibolga'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Simalungun'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Pematangsiantar'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Deli Serdang'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Mandailing Natal'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Toba Samosir'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Tengah'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Simalungun'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Dairi'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Utara'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Pakpak Barat'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Dairi'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Langkat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias Barat'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Tengah'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias'],
            ['nama' => 'Seksi Urusan Agama Kristen Kantor Kementerian Agama Kota Gunungsitoli', 'parent_nama' => 'Kantor Kementerian Agama Kota Gunungsitoli'],
            ['nama' => 'Penyelenggara Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Samosir'],
            ['nama' => 'Seksi Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Selatan'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Labuhanbatu Selatan'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias Utara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Padang Lawas Utara'],
            ['nama' => 'Bidang Bimbingan Masyarakat Kristen', 'parent_nama' => 'Kanwil Kementerian Agama Provinsi Sumatera Utara'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Asahan'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Tapanuli Utara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kota Tebing Tinggi'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Samosir'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Karo'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Karo'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Humbang Hasundutan'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Humbang Hasundutan'],
            ['nama' => 'Seksi Urusan Agama Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias Selatan'],
            ['nama' => 'Seksi Pendidikan Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Nias Barat'],
            ['nama' => 'Penyelenggara Pendidikan Kristen Kantor Kementerian Agama Kota Gunungsitoli', 'parent_nama' => 'Kantor Kementerian Agama Kota Gunungsitoli'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Labuhanbatu Utara'],
            ['nama' => 'Penyelenggara Kristen', 'parent_nama' => 'Kantor Kementerian Agama Kabupaten Labuhanbatu'],
            ['nama' => 'Jurusan Pendidikan Agama Kristen', 'parent_nama' => 'Jurusan Pendidikan Agama Kristen'],
        ];
        $sk2Inserted = 0;
        foreach ($satuanKerja2Pairs as $pair) {
            $parentId = $this->findIdByName('satuan_kerja', $pair['parent_nama']);
            if ($parentId === null) {
                echo "  [WARNING] Satuan Kerja tidak ditemukan: {$pair['parent_nama']}\n";
                continue;
            }
            $this->insertIfNotExists('satuan_kerja_2', ['nama' => $pair['nama'], 'parent_id' => $parentId], $now);
            $sk2Inserted++;
        }
        echo "Satuan Kerja 2: {$sk2Inserted} pasangan diproses.\n";
    }

    /**
     * Insert satu baris ke tabel lookup HANYA kalau kombinasi field yang
     * diberikan belum ada (idempotent — aman dijalankan berulang kali).
     */
    private function insertIfNotExists(string $table, array $fields, string $now): void
    {
        $query = $this->db->table($table);
        foreach ($fields as $key => $value) {
            $query->where($key, $value);
        }
        if ($query->countAllResults() > 0) {
            return;
        }

        $this->db->table($table)->insert(array_merge($fields, [
            'is_active'  => 1,
            'created_at' => $now,
            'updated_at' => $now,
        ]));
    }

    /**
     * Cari id berdasarkan nama (exact match, trimmed).
     */
    private function findIdByName(string $table, string $nama): ?int
    {
        $row = $this->db->table($table)->select('id')->where('nama', $nama)->get()->getRowArray();
        return $row['id'] ?? null;
    }
}
